swagger: "2.0"
info:
    title: authentication
    description: crop yield monitor
    version: ""
host: 0.0.0.0:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /healthz:
        get:
            tags:
                - servers
            summary: get health servers
            operationId: servers#get health
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ServersGetHealthResponseBody'
            schemes:
                - http
    /login:
        post:
            tags:
                - servers
            summary: login servers
            operationId: servers#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ServersLoginRequestBody'
                    required:
                        - username
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ServersLoginResponseBody'
            schemes:
                - http
    /openapi3.json:
        get:
            tags:
                - servers
            summary: Download ./gen/http/openapi3.json
            operationId: servers#/openapi3.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /signup:
        post:
            tags:
                - servers
            summary: signup servers
            operationId: servers#signup
            parameters:
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ServersSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ServersSignupResponseBody'
            schemes:
                - http
    /swaggerui/{path}:
        get:
            tags:
                - servers
            summary: Download ./swaggerui
            operationId: servers#/swaggerui/{*path}
            parameters:
                - name: path
                  in: path
                  description: Relative file path
                  required: true
                  type: string
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
                "404":
                    description: File not found
                    schema:
                        $ref: '#/definitions/Error'
            schemes:
                - http
definitions:
    Error:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Error response result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ServersGetHealthResponseBody:
        title: ServersGetHealthResponseBody
        type: object
        properties:
            msg:
                type: string
                description: message
                example: Est qui et.
        example:
            msg: Est doloribus sunt.
    ServersLoginRequestBody:
        title: ServersLoginRequestBody
        type: object
        properties:
            password:
                type: string
                description: Password
                example: "77777"
                minLength: 1
            username:
                type: string
                description: Username
                example: demo
                minLength: 1
        example:
            password: "77777"
            username: demo
        required:
            - username
            - password
    ServersLoginResponseBody:
        title: ServersLoginResponseBody
        type: object
        properties:
            error:
                type: string
                description: error reason
                example: Porro deserunt consequatur enim fugiat magnam deleniti.
            ok:
                type: boolean
                description: operation successful?
                example: true
            uuid:
                type: string
                description: unique user identification
                example: Omnis modi laboriosam corporis.
        example:
            error: Sit eligendi voluptate.
            ok: false
            uuid: Dolorem repellendus reiciendis.
    ServersSignupRequestBody:
        title: ServersSignupRequestBody
        type: object
        properties:
            emailid:
                type: string
                description: emailid
                example: demo@xyz.com
            first:
                type: string
                description: first name
                example: hello
            last:
                type: string
                description: last name
                example: world
            password:
                type: string
                description: password
                example: "77777"
        example:
            emailid: demo@xyz.com
            first: hello
            last: world
            password: "77777"
    ServersSignupResponseBody:
        title: ServersSignupResponseBody
        type: object
        properties:
            error:
                type: string
                description: error reason
                example: Dolorem aspernatur.
            ok:
                type: boolean
                description: operation successful?
                example: true
            uuid:
                type: string
                description: unique user identification
                example: Voluptas temporibus expedita eum aut sunt doloribus.
        example:
            error: Autem vel debitis.
            ok: true
            uuid: Voluptates et.
